colorCombos = ["TrueGreen, TrueBlue", "FalseGreen, FalseBlue", "TrueBlue, TruePurple", "TrueBlue, TruePink", "TrueRed, TrueGray", "FalseRed, TrueGray", "TrueOrange, TrueGray", "TrueGreen, TrueGray", "FalseGreen, TrueGray", "TrueBlue, TrueGray", "FalseBlue, TrueGray", "TruePurple, TrueGray", "FalsePurple, TrueGray", "TruePink, TrueGray", "FalseGray, TrueGray", "TrueBeige, FalseGray", "FalseBeige, TrueGray", "TrueBrown, TrueGray", "FalseBrown, TrueGray", "TrueWhite, TrueGray", "FalseWhite, TrueGray", "TrueBlack, TrueGray", "FalseBlack, TrueGray", "TrueRed, FalseGray", "TrueGreen, FalseGray", "FalseGreen, FalseGray", "TrueBlue, FalseGray", "FalseBlue, FalseGray", "TruePurple, FalseGray", "FalsePurple, FalseGray", "TruePink, FalseGray", "TrueBeige, FalseGray", "TrueWhite, FalseGray", "FalseWhite, FalseGray", "TrueBlack, FalseGray", "FalseBlack, FalseGray", "TrueRed, TrueBeige", "FalseRed, TrueBeige", "TrueOrange, TrueBeige", "TrueGreen, TrueBeige", "FalseGreen, TrueBeige", "TrueBlue, TrueBeige", "FalseBlue, TrueBeige", "TruePurple, TrueBeige", "FalsePurple, TrueBeige", "TruePink, TrueBeige", "TrueGray, TrueBeige", "TrueBrown, TrueBeige", "FalseBrown, TrueBeige", "TrueWhite, TrueBeige", "FalseWhite, TrueBeige", "TrueBlack, TrueBeige", "FalseBlack, TrueBeige", "TrueRed, FalseBeige", "TrueGreen, FalseBeige", "FalseGreen, FalseBeige", "TrueBlue, FalseBeige", "FalseBlue, FalseBeige", "TruePurple, FalseBeige", "TruePink, FalseBeige", "TrueRed, TrueBrown", "TrueYellow, TrueBrown", "TrueGreen, TrueBrown", "FalseGreen, TrueBrown", "TrueBlue, TrueBrown", "FalseBlue, TrueBrown", "TruePurple, TrueBrown", "FalsePurple, TrueBrown", "TruePink, TrueBrown", "TrueWhite, TrueBrown", "FalseWhite, TrueBrown", "TrueBlack, TrueBrown", "FalseBlack, TrueBrown", "TrueRed, FalseBrown", "TrueOrange, FalseBrown", "TrueYellow, FalseBrown", "TrueGreen, FalseBrown", "FalseGreen, FalseBrown", "TrueBlue, FalseBrown", "FalseBlue, FalseBrown", "TruePurple, FalseBrown", "FalsePurple, FalseBrown", "TrueBeige, FalseBrown", "FalseBeige, FalseBrown", "TrueWhite, FalseBrown", "FalseWhite, FalseBrown", "TrueBlack, FalseBrown", "FalseBlack, FalseBrown", "TrueWhite, TrueWhite", "TrueWhite, FalseWhite", "FalseWhite, FalseWhite", "TrueBlack, TrueBlack", "TrueBlack, FalseBlack", "FalseBlack, FalseBlack"]

outerwear = ["Sweater", "Hoodie", "Zip-Up Jacket", "Coat", "Cardigan"]

# Under 70 degrees Fahrenheit
coldT = ["Short Sleeve Top", "Long Sleeve Top"]
coldB = ["Jeans", "Dress Pants", "Leggings", "Sweatpants", "Maxi Skirt"]

# Over 70 degrees Fahrenheit
warmT = ["Short Sleeve Top", "Long Sleeve Top", "Tank Top"]
warmB = ["Leggings", "Short Shorts", "Mid Length Shorts", "Knee Length Shorts", "Miniskirt", "Knee Length Skirt"]